### ISSUE TITLE
set_timeout failure on NodeJS

### ISSUE THREAD

**Issue by b-zee** [whizsid/wasmtimer-rs#18]
I have a package that is built with `wasm-pack` (as `nodejs` pkg). Then run `node index.js` with the following contents:
```js
// index.js
import * as mymodule from '../pkg/mymodule.js';
const client = await mymodule.connect(["xxx"]);
```

Looks like `set_timeout_with_callback_and_timeout_and_arguments_0` is somehow called with an 'object'. I've looked at the source of this library, but can't put my finger on it. As far as I can tell, the library passes an `i32`.

https://github.com/whizsid/wasmtimer-rs/blob/d986a6311905eda311b80673ff64f830800cf87f/src/js.rs#L38

Full error given by `node index.js`:

```txt
panicked at /home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtimer-0.2.1/src/timer/global.rs:85:6:
called `Result::unwrap()` on an `Err` value: JsValue(Error: expected a number argument, found object
Error: expected a number argument, found object
    at _assertNum (/home/src/pkg/mypackage.js:122:39)
    at /home/src/pkg/mypackage.js:975:5
    at handleError (/home/src/pkg/mypackage.js:337:18)
    at module.exports.__wbg_setTimeout_2cb6c793c4aa44f8 (/home/src/pkg/mypackage.js:973:72)
    at mypackage.wasm.wasmtimer::js::GlobalScope::set_timeout_with_callback_and_timeout_and_arguments_0::hc5937d4261cc26d3 (wasm://wasm/mypackage.wasm-081c0c9e:wasm-function[14952]:0x12184c9)
    at mypackage.wasm.wasmtimer::js::set_timeout::hdb2b1538b11fcdb7 (wasm://wasm/mypackage.wasm-081c0c9e:wasm-function[32593]:0x1575242)
    at mypackage.wasm.wasmtimer::timer::global::schedule_callback::hdf324c5b5eac0d8f (wasm://wasm/mypackage.wasm-081c0c9e:wasm-function[14154]:0x11da86c)
    at mypackage.wasm.wasmtimer::timer::global::run::h2c65363f7d360fb5 (wasm://wasm/mypackage.wasm-081c0c9e:wasm-function[22148]:0x13ce6df)
    at mypackage.wasm.<wasmtimer::timer::TimerHandle as core::default::Default>::default::h8c6e04d833f584ff (wasm://wasm/mypackage.wasm-081c0c9e:wasm-function[10330]:0x1075473)
    at mypackage.wasm.wasmtimer::tokio::sleep::Sleep::new_at::hd912f3bbeb63e925 (wasm://wasm/mypackage.wasm-081c0c9e:wasm-function[42648]:0x166c400))

Stack:

Error
    at /home/src/pkg/mypackage.js:633:17
    at logError (/home/src/pkg/mypackage.js:240:18)
    at module.exports.__wbg_new_abda76e883ba8a5f (/home/src/pkg/mypackage.js:632:65)
    at mypackage.wasm.console_error_panic_hook::Error::new::h927f5ef14249f64a (wasm://wasm/mypackage.wasm-081c0c9e:wasm-function[40613]:0x16412fd)
    at mypackage.wasm.console_error_panic_hook::hook_impl::h2ada2845e01813dd (wasm://wasm/mypackage.wasm-081c0c9e:wasm-function[11972]:0x111c8d3)
    at mypackage.wasm.console_error_panic_hook::hook::hec432ab322f3ce21 (wasm://wasm/mypackage.wasm-081c0c9e:wasm-function[68992]:0x174a40e)
    at mypackage.wasm.core::ops::function::Fn::call::h16c185a06c60eb93 (wasm://wasm/mypackage.wasm-081c0c9e:wasm-function[46670]:0x16b35ae)
    at mypackage.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/mypackage.wasm-081c0c9e:wasm-function[21235]:0x13a02d4)
    at mypackage.wasm.std::panicking::begin_panic_handler::{{closure}}::h98de848d678bad07 (wasm://wasm/mypackage.wasm-081c0c9e:wasm-function[29773]:0x15169d5)
    at mypackage.wasm.std::sys::backtrace::__rust_end_short_backtrace::h2bcfc60c3cf0a312 (wasm://wasm/mypackage.wasm-081c0c9e:wasm-function[71905]:0x1751573)


wasm://wasm/mypackage.wasm-081c0c9e:1


RuntimeError: unreachable
    at mypackage.wasm.__rust_start_panic (wasm://wasm/mypackage.wasm-081c0c9e:wasm-function[73324]:0x1753368)
    at mypackage.wasm.rust_panic (wasm://wasm/mypackage.wasm-081c0c9e:wasm-function[65781]:0x17413b5)
    at mypackage.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (wasm://wasm/mypackage.wasm-081c0c9e:wasm-function[21235]:0x13a0302)
    at mypackage.wasm.std::panicking::begin_panic_handler::{{closure}}::h98de848d678bad07 (wasm://wasm/mypackage.wasm-081c0c9e:wasm-function[29773]:0x15169d5)
    at mypackage.wasm.std::sys::backtrace::__rust_end_short_backtrace::h2bcfc60c3cf0a312 (wasm://wasm/mypackage.wasm-081c0c9e:wasm-function[71905]:0x1751573)
    at mypackage.wasm.rust_begin_unwind (wasm://wasm/mypackage.wasm-081c0c9e:wasm-function[42684]:0x166d0ba)
    at mypackage.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (wasm://wasm/mypackage.wasm-081c0c9e:wasm-function[44404]:0x168d63d)
    at mypackage.wasm.core::result::unwrap_failed::h472431483d5eea7f (wasm://wasm/mypackage.wasm-081c0c9e:wasm-function[32285]:0x156bb9a)
    at mypackage.wasm.wasmtimer::timer::global::schedule_callback::hdf324c5b5eac0d8f (wasm://wasm/mypackage.wasm-081c0c9e:wasm-function[14154]:0x11da8da)
    at mypackage.wasm.wasmtimer::timer::global::run::h2c65363f7d360fb5 (wasm://wasm/mypackage.wasm-081c0c9e:wasm-function[22148]:0x13ce6df)
```

**Comment by whizsid** [comment]
@b-zee I am not sure which functions you used for your project. But I added a NodeJS example project to cover important functions. https://github.com/whizsid/wasmtimer-rs/tree/master/examples/nodejs-example . Can you provide the NodeJS version that you are testing?

**Comment by b-zee** [comment]
It seems to happen because of `tokio::select!`:

```rust
#[wasm_bindgen]
pub async fn my_fn() {
    async fn some_async_work() {
        wasmtimer::tokio::sleep(std::time::Duration::from_secs(1)).await;
    }

    loop {
        tokio::select! {
            _ = some_async_work() => { break },
        }
    }
}
```

**Comment by whizsid** [comment]
@b-zee I also tested it with the `select` macro. https://github.com/whizsid/wasmtimer-rs/tree/nodejs-example-tokio-macros/examples/nodejs-example . But could not replicate that. I am also testing it on Node 22.

**Comment by whizsid** [comment]
@b-zee Thank you for investigating it. I could replicate that issue. The `wasm-bindgen` is generating a debug glue around the second parameter of `setTimeout`. Then that value automatically converted to an `object` instead of a `number`. Unfortunately we do not have any way to control it from the crate level. This issue (https://github.com/rustwasm/wasm-bindgen/issues/1666) is mentioning the same problem. 

However you can add below lines to `Cargo.toml` to fix the error. But it is only working for the project's `Cargo.toml` file. Otherwise I could add it to the crate’s manifest to fix the issue.
```toml
[package.metadata.wasm-pack.profile.dev.wasm-bindgen]
# Should we enable wasm-bindgen's debug assertions in its generated JS glue?
debug-js-glue = false
```

**Comment by b-zee** [comment]
Super insightful comment there @whizsid. Thanks a lot for providing a workaround. Super curious how you figured this out.

**Comment by matheus23** [comment]
> However you can add below lines to `Cargo.toml` to fix the error. But it is only working for the project's `Cargo.toml` file. Otherwise I could add it to the crate’s manifest to fix the issue.

We're building a library here, so that's not going to cut it for us.

The underlying issue is that while on the web the value returned from `setTimeout` is indeed a `number`, that's not the case for `nodejs`:

```js
$ node
Welcome to Node.js v20.15.1.
Type ".help" for more information.
> setTimeout(() => console.log("Hi!"), 1000)
Timeout {
  _idleTimeout: 1000,
  _idlePrev: [TimersList],
  _idleNext: [TimersList],
  _idleStart: 3092,
  _onTimeout: [Function (anonymous)],
  _timerArgs: undefined,
  _repeat: null,
  _destroyed: false,
  [Symbol(refed)]: true,
  [Symbol(kHasPrimitive)]: false,
  [Symbol(asyncId)]: 29,
  [Symbol(triggerId)]: 6
}
> Hi!
```

But your bindings actually still refer to the return value of `setTimeout` as `Result<i32, JsValue>`:
https://github.com/whizsid/wasmtimer-rs/blob/7a5f83f98bed85e8d3c20c259ccebeaa9487bf62/src/js.rs#L17-L22

IMO the fix is to change that return value to an opaque `JsValue`, that one can then either be `number` or `Object` in practice.
This also still works with `clearTimeout`, which in the both browsers and nodejs needs to be passed the return value of `setTimeout`.
